config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, only: [:new, :index, :show, :edit, :create, :destroy, :update]
  resources :users, only: [:index, :show, :edit, :create, :update]
  root to: 'homes#top'
  get 'home/about' => "homes#about", as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy

  validates :name, length: { minimum: 2 }
  validates :name, presence: true, length: { maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  validates :name, uniqueness: true
  validates :email, uniqueness: true



  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :correct_user, only: [:edit, :update]
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end



  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user =current_user
    @books =Book.all
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @users = @book.user
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


 private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  # def correct_user
    # @book = Book.find(params[:id])
    # @user = @book.user
    # redirect_to(books_path) unless @user == current_user
  # end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def edit
     @user = User.find(params[:id])
      redirect_to user_path(current_user[:id]) unless @user == current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  # def correct_user
    # @user = User.find(params[:id])
    # redirect_to user_path(current_user[:id]) unless @user == current_user
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_sidebar.html.erb
 <div class ="col-md-3">
      <!--ここからユーザ情報-->
      <!--あとで-->
      <h2>User info</h2>
      <%= image_tag user.get_profile_image %> </br>
      <table class ="table">
        <tr>
          <th>Name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>Introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </table>
      <div class ="row">
        <a class="btn btn-outline-secondary btn-block" href ="/users/<%=user.id %>/edit">
          <i class="fas fa-user-cog"></i>
        </a>
      </div>
      <!--ここから投稿フォーム-->
      <h2>New book</h2>
      <%= form_with model: book do |f| %>
          <div class ="form-group">
            <label>Title</label> </br>
            <%= f.text_field :title %>
          </div>
          <div class ="form-group">
            <label>Opinion</label> </br>
            <%= f.text_area :body %>
          </div>
          <div class ="form-group">
            <%= f.submit 'Create Book', class: "btn btn-secondary" %>
          </div>
      <% end %>
    </div>

app/views/books/edit.html.erb
<div class ="container">
  <div class ="row text-left">
    <div class ="col-sm-12 col-md-8 mx-auto">
      <h1>Editing Book</h1>
      <div class ="error_explanation">
        <!--エラー文-->
        <% if @book.errors.any? %>
          <%= @book.errors.count %>errors prohibited this obj from being saved:
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
        <%= form_with model: @book do |f| %>
        <div class ="form-group">
          <label for=inputtitle>Title</label> </br>
          <%= f.text_field :title, autofocus: true, id:"inputtitle" %>
        </div>
        <div class ="form-group">
          <label for=inputbody>Opinion</label> </br>
          <%= f.text_area :body, autofocus: true, id:"inputbody" %>
        </div>
        <div class ="form-group">
          <%= f.submit "Update Book", class: "btn btn-secondary" %>
        </div>
        <% end %>
      <%= link_to "Show", book_path %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class ="container px-5 px-sm-0">
  <div class ="error_explanation">
    <!--エラー文-->
    <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this obj from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class ="row">
    <%= render 'sidebar', book: @book, user: @user %>
      <div class ="col-md-8 offset-md-1">
        <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
            </tr>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <a href="/users/<%=book.user.id%>">
                    <%= image_tag book.user.get_profile_image %>
                    </a>
                </td>
                <td>
                  <a href="/books/<%= book.id %>"><%= book.title %></a>
                </td>
                <td>
                  <%= book.body %>
                </td>
                <td>
                </td>
              </tr>
            <% end %>
          </table>
      </div>
  </div>
</div>

app/views/books/show.html.erb
<div class ="container px-5 px-sm-0">

  <div class="row">
    <%= render 'sidebar', book: @books, user: @users%>
    <div class ="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class ="table">
        <tr>
          <th>
            <a href="/users/<%= @users.id %>"><%= image_tag @users.get_profile_image %> </a></br>
            <a href="/users/<%= @users.id %>"><%= @users.name %></a>
          </th>
          <th>
            <a href="/books/<%=@book.id%>"><%= @book.title %></a>
          </th>
          <th>
            <%= @book.body %>
          </th>
          <% if @users == current_user %>
          <th>
            <%= link_to "Edit", edit_book_path(@book), class: "btn btn-secondary" %>
          </th>
          <th>
              <%= link_to "Destroy", book_path(@book), method: :delete,"data-confirm" => "本当に削除しますか？", class: "btn btn-secondary" %>
          </th>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class ="container">
  <div class ="row">
      <h1 class ="px-3 mx-auto">
        Welcom to <i class="fas fa-book"></i><strong>Bookers</strong>
      </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class ="container">
  <div class ="row">
    <div class ="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        Welcom to <i class="fas fa-book"></i><strong>Bookers</strong>
      </h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers,</strong></p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class ="btn-wrapper col-10 mx-auto">
        <div class ="row">
          <a class ="btn btn-info btn-sm btn-block mb-3 sign_in" href ="/users/sign_in">Log in</a>
        </div>
        <div class ="row">
          <a class ="btn btn-info btn-sm btn-block mb-3 sign_up" href ="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class ="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class ="container">
          <div class ="navbar-brand navbar-nav nav-link ">
            <%= link_to "Bookers", root_path %>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class ="collapse navbar-collapse"  id="navbarNavDropdown">
            <ul class ="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class ="nav-item nav-link">
                <i class="fas fa-home"></i><%= link_to "Home", user_path(current_user) %>
              </li>
              <li class ="nav-item nav-link" >
                <i class="fas fa-users"></i><%= link_to "Users", users_path %>
              </li>
              <li class ="nav-item nav-link">
                <i class="fas fa-book-open"></i><%= link_to "Books", books_path %>
              </li>
              <li class ="nav-item nav-link">
                 <i class="fas fa-sign-out-alt"></i><%= link_to "Log out", destroy_user_session_path, method: :delete %>
              </li>
              <% else %>
              <li class ="nav-item nav-link">
                <i class="fas fa-home"></i><%= link_to "Home", root_path %>
              </li>
              <li class ="nav-item nav-link">
                <i class="fas fa-link"></i><%= link_to "About", about_path %>
              </li>
              <li class ="nav-item nav-link">
                <i class="fas fa-user-plus"></i><%= link_to "Sign up", new_user_registration_path %>
              </li>
              <li class ="nav-item nav-link">
                <i class="fas fa-sign-in-alt"></i><%= link_to "Log in", new_user_session_path %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= flash[:notice] %>
      <%= yield %>
    </main>
    <footer>
      <div class ="container mt-5">
        <div class ="row">
          <div class ="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_sidebar.html.erb
 <div class ="col-md-3">
      <!--ここからユーザ情報-->
      <!--あとで-->
      <h2>User info</h2>
      <%= image_tag user.get_profile_image %> </br>
      <table class ="table">
        <tr>
          <th>Name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>Introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </table>
      <div class ="row">
        <a class="btn btn-outline-secondary btn-block" href ="/users/<%= user.id %>/edit">
          <i class="fas fa-user-cog"></i>
        </a>
      </div>
      <!--ここから投稿フォーム-->
      <h2>New book</h2>
      <%= form_with model: book do |f| %>
          <div class ="form-group">
            <label>Title</label> </br>
            <%= f.text_field :title %>
          </div>
          <div class ="form-group">
            <label>Opinion</label> </br>
            <%= f.text_area :body %>
          </div>
          <div class ="form-group">
            <%= f.submit 'Create Book', class: "btn btn-secondary" %>
          </div>
      <% end %>
    </div>

app/views/users/edit.html.erb
<div class ="container">
  <div class ="row text-left">
    <div class ="col-sm-12 col-md-8 mx-auto">
      <h1>Editing</h1>
      <div class ="error_explanation">
        <!--エラー文-->
        <% if @user.errors.any? %>
          <%= @user.errors.count %>errors prohibited this obj from being saved:
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
        <%= form_with model: @user do |f| %>
        <div class ="form-group">
          <label for="inputname">Name</label> </br>
          <%= f.text_field :name, autofocus: true, id:"inputname" %>
        </div>
        <div class ="form-group">
          <label for="input">Image</label> </br>
          <%= f.file_field :profile_image, accept: "image/*" %>
        </div>
        <div class ="form-group">
          <label for="inputintroduction">Introduction</label> </br>
          <%= f.text_area :introduction, autofocus: true, id:"inputintroduction" %>
        </div>
        <div class ="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class ="container px-5 px-sm-0">
  <div class ="row">
    <%= render 'sidebar', book: @book, user: @user %>
      <div class ="col-md-8 offset-md-1">
        <h2>Users</h2>
          <table class="table table-hover table-inverse">
            <tr>
              <th>Image</th>
              <th>Name</th>
              <th> </th>
            </tr>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= image_tag user.get_profile_image %>
                </td>
                <td>
                  <%= user.name %>
                </td>
                <td>
                  <%= user.introduction %>
                </td>
                <td>
                  <%= link_to "Show", user_path(user.id) %>
                </td>
              </tr>
            <% end %>
          </table>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class ="container px-5 px-sm-0">
  <div class ="row">
    <%= render 'sidebar', book: @book, user: @user %>
      <div class ="col-md-8 offset-md-1">
        <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
            </tr>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <a href="/users/<%=@user.id%>"><%= image_tag @user.get_profile_image %></a> </br>
                </td>
                <td>
                  <a href="/books/<%= book.id %>"><%= book.title %></a>
                </td>
                <td>
                  <%= book.body %>
                </td>
                <td>
                </td>
              </tr>
            <% end %>
          </table>
      </div>
  </div>
</div>